services:
  norrna:
    image: norrna:local
    build:
      context: .
      dockerfile: Dockerfile.release
    container_name: norrna
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      WEBPORT: "3000"
      AGENTPORT: "3001"
      DATA_DIR: /data
    volumes:
      - norrna-data:/data

volumes:
  norrna-data:
